version: "3"
services:
  app:
    container_name: user-system
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
