version: 2.1
orbs:
  node: circleci/node@4.7
  sonarcloud: sonarsource/sonarcloud@1.1.0
jobs:
  build-and-test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - sonarcloud/scan
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
workflows:
  main:
    jobs:
      - build-and-test:
          context: sonarcloud
